openapi: "3.1.0"
info:
  title: "TableTennisTrainingSystem API"
  description: "API documentation for the Table Tennis Training System"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /user/signup:
    post:
      summary: "用户注册"
      description: "允许学生或教练注册账户"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "201":
          description: "注册成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                  userId:
                    type: "string"
        "400":
          description: "请求参数错误"
          content:
            text/plain:
              schema:
                type: "string"
  /user/login:
    post:
      summary: "用户登录"
      description: "通过表单验证用户身份"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
              required:
                - "username"
                - "password"
      responses:
        "200":
          description: "登录成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: "认证失败"
  /user/logout:
    post:
      summary: "用户登出"
      description: "清除用户会话"
      responses:
        "200":
          description: "登出成功"
  /user/info:
    get:
      summary: "获取用户信息"
      description: "获取当前登录用户的信息"
      responses:
        "200":
          description: "返回用户信息"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: "未认证"
    put:
      summary: "更新用户信息"
      description: "更新当前登录用户的信息"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: "更新成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
        "400":
          description: "请求参数错误"
        "401":
          description: "未认证"
  /user/create:
    post:
      summary: "创建用户"
      description: "超级管理员创建校区管理员"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "201":
          description: "创建成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                  userId:
                    type: "string"
        "400":
          description: "请求参数错误"
        "401":
          description: "未认证"
        "403":
          description: "权限不足"
  /user/{userId}:
    delete:
      summary: "删除用户"
      description: "超级管理员删除校区管理员"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "删除成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
        "400":
          description: "请求参数错误"
        "401":
          description: "未认证"
        "403":
          description: "权限不足"
  /user/{userId}/reset-password:
    put:
      summary: "重置用户密码"
      description: "超级管理员重置校区管理员密码"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "重置成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
        "400":
          description: "请求参数错误"
        "401":
          description: "未认证"
        "403":
          description: "权限不足"
  /:
    get:
      summary: "根路径"
      description: "测试服务器是否运行"
      responses:
        "200":
          description: "服务器正常运行"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
components:
  schemas:
    User:
      type: "object"
      properties:
        uuid:
          type: "string"
          nullable: true
        username:
          type: "string"
        plainPassword:
          type: "string"
          nullable: true
        encryptedPassword:
          type: "string"
          nullable: true
        realName:
          type: "string"
        gender:
          type: "string"
        age:
          type: "integer"
          format: "int32"
        phoneNumber:
          type: "string"
        email:
          type: "string"
        campusId:
          type: "integer"
          format: "int32"
        role:
          type: "string"
          enum:
            - "SUPER_ADMIN"
            - "CAMPUS_ADMIN"
            - "COACH"
            - "STUDENT"
        status:
          type: "string"
        createdAt:
          type: "string"
          format: "date-time"
          nullable: true
        lastLoginAt:
          type: "string"
          format: "date-time"
          nullable: true
        studentInfo:
          $ref: "#/components/schemas/StudentInfo"
          nullable: true
        coachInfo:
          $ref: "#/components/schemas/CoachInfo"
          nullable: true
      required:
        - "username"
        - "realName"
        - "gender"
        - "age"
        - "phoneNumber"
        - "email"
        - "campusId"
        - "role"
        - "status"
    StudentInfo:
      type: "object"
      properties:
        balance:
          type: "number"
          format: "float"
        maxCoach:
          type: "integer"
          format: "int32"
        currentCoach:
          type: "integer"
          format: "int32"
      required:
        - "balance"
        - "maxCoach"
        - "currentCoach"
    CoachInfo:
      type: "object"
      properties:
        photoUrl:
          type: "string"
          nullable: true
        achievements:
          type: "string"
          nullable: true
        level:
          type: "string"
          nullable: true
        hourlyRate:
          type: "number"
          format: "float"
        balance:
          type: "number"
          format: "float"
        maxStudents:
          type: "integer"
          format: "int32"
        currentStudents:
          type: "integer"
          format: "int32"
        isApproved:
          type: "boolean"
        approvedBy:
          type: "integer"
          format: "int32"
      required:
        - "hourlyRate"
        - "balance"
        - "maxStudents"
        - "currentStudents"
        - "isApproved"
        - "approvedBy"